name: Rust Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Add x86_64-pc-windows-gnu target
      run: rustup target add x86_64-pc-windows-gnu

    - name: Add i686-pc-windows-gnu target
      run: rustup target add i686-pc-windows-gnu

    - name: Build for x86_64-pc-windows-gnu
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Build for i686-pc-windows-gnu
      run: cargo build --release --target i686-pc-windows-gnu

    - name: Upload DLLs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chuniio-backflow-dlls
        path: |
          target/x86_64-pc-windows-gnu/release/chuniio_backflow.dll
          target/i686-pc-windows-gnu/release/chuniio_backflow.dll

