name: Rust Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu, i686-pc-windows-gnu
        override: true

    - name: Build for x86_64-pc-windows-gnu
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Build for i686-pc-windows-gnu
      run: cargo build --release --target i686-pc-windows-gnu

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chuniio-backflow-dlls
        path: |
          target/x86_64-pc-windows-gnu/release/chuniio_backflow.dll
          target/i686-pc-windows-gnu/release/chuniio_backflow.dll
          
